### ISSUE TITLE
Questioning password strength checks

### ISSUE THREAD

**Issue by astrostl** [SummitRoute/osxlockdown#11]
As per https://github.com/SummitRoute/osxlockdown/issues/6 , is `tr` even necessary?

Mostly, though, writing to express doubt about the checks. As per the `pwpolicy` man page, "maxFailedLoginAttempts" intructs that "user's account is disabled if the failed login count exceeds this number." Is this safe on single-user systems? Not inspired to test.

Further, things like numbers, caps, and symbols don't do much to move the needle on entropy, but sure make things harder to remember and type. https://xkcd.com/936/ is a famous pop example of this, and https://en.wikipedia.org/wiki/Diceware is a nice implementation.

**Comment by astrostl** [comment]
I think minimum length requirements are great. Would keep that, ditch the rest.

**Comment by 0xdabbad00** [comment]
Great point about not setting maxFailedLoginAttempts.  Yikes. Sorry about that.

I'm going to just delete this rule for now.  To reset one's password policies they can use:

```
pwpolicy clearaccountpolicies
```

Looks like if anyone locks themselves out, they can still recover using this procedure: https://support.apple.com/en-us/HT203114

I'm a little concerned that such a procedure exists.
