### ISSUE TITLE
Feature: Disable automatic loading of remote content Mail.app

### ISSUE THREAD

**Issue by vivami** [SummitRoute/osxlockdown#15]
I've added a check and fix to disable automatically loading of remote content by Mail.app when an email is opened by the user: `defaults write com.apple.mail-shared DisableURLLoading -bool true` 

![screenshot](http://f.cl.ly/items/0C3Y1R0W3s2y18102G1s/remote_content.png)

This should prevent Mail from automatically loading possibly malicious content from (hidden) URLs in e-mails.
I [have forked and did a pull request](https://github.com/SummitRoute/osxlockdown/pull/16), but since this is my first time, not sure whether I did it right...

**Comment by 0xdabbad00** [comment]
Your PR https://github.com/SummitRoute/osxlockdown/pull/16 worked great. Thank you.
