### ISSUE TITLE
FileVault / Hibernation Configuration

### ISSUE THREAD

**Issue by gepeto42** [SummitRoute/osxlockdown#3]
Hi,

As your script seems to be more "aggressive" than conservative (not saying this as a negative, quite the opposite), would you consider verifying hibernation modes and FileVault key destruction on sleep with pmset and configuring the following?

Hibernatemode to 25
Destroyfvkeysonstandby to 1

Thanks!

**Comment by jeroenvisser101** [comment]
What exactly does the `hibernatemode` change? The destruction of the key makes total sense to me.

**Comment by gepeto42** [comment]
Hibernation modes -> 0 (disabled), 3 (Smart - it sleeps and prepares the hibernation file) and 25 disables sleeps, so memory is empty and resume only happens from the hibernation file.

**Comment by 0xdabbad00** [comment]
Awesome! Added in https://github.com/SummitRoute/osxlockdown/commit/748e354f0675a07e7dc8793c9c0563347428a72c

**Comment by anton48** [comment]
actually, such settings will turn off some notebooks instead of sleeping, you may check long explanation and the fix there: https://derflounder.wordpress.com/2014/02/12/power-nap-power-management-settings-and-filevault-2/
