### ISSUE TITLE
Sparkle updater http option failed to fix.

### ISSUE THREAD

**Issue by ghost** [SummitRoute/osxlockdown#36]
Title says everything, auditing and fixing it fails.

**Comment by 0xdabbad00** [comment]
There is currently no fix for the sparkle updater check. It needs to be fixed manually by identifying the apps that are causing the failure and requesting the developer of that application fix their update process.  From my end, I plan on improving osxcollector so it will provide more information about how to check what apps are causing that failure.

**Comment by TraderStf** [comment]
FYI, several batch cmd
https://github.com/sparkle-project/Sparkle/issues/717#issuecomment-186542146
