### ISSUE TITLE
Disable IPv6 (or rather, don't)

### ISSUE THREAD

**Issue by virtuallynathan** [SummitRoute/osxlockdown#4]
IPv6 should not be disabled. I'm not sure what this adds security-wise.

**Comment by jeroenvisser101** [comment]
I think that's since IPv6 doesn't require ~~DHCP~~ NAT (since there are so many addresses available), thus giving all computers a publicly accessable IP.

**Comment by gepeto42** [comment]
Usually it's more about reducing attack surface, and making sure that if you don't use something, it's disabled. Enterprise who do not use IPv6 (or THINK they don't) can have issues around weak firewall policies on IPv6, assuming IPv4 is the only path, etc.

@virtuallynathan: I know some Linux distros do not react well to complete IPv6 deactivation (like removing the module). Is there any similar impact that you are aware of on OS X?

**Comment by virtuallynathan** [comment]
NAT is security through obscurity, most home/enterprise routers implement a stateful IPv6 firewall by default -- this provides the security of NAT without the obscurity. 

IPv6 is no longer a kernel module in Linux, it is part of the kernel. I am not sure about OS X, but it is likely headed that way. Starting in 2016, all iOS 9 apps must work in IPv6 only environments. https://developer.apple.com/library/ios/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/UnderstandingandPreparingfortheIPv6Transition/UnderstandingandPreparingfortheIPv6Transition.html

**Comment by gepeto42** [comment]
I agree with you that NAT shouldn't be considered a security feature, and that IPv6 should probably not be automatically disabled anymore, but I would say NAT is more than just obscurity - it actually prevents connections back to hosts from the Internet. Not saying it's anything more than what a FW could do, but it's more than "just obscurity".

That being said especially with Apple moving to more and more IPv6, in my opinion, it should probably be an "optional" setting for people who do not want IPv6 in their environment yet, but not the default.

**Comment by 0xdabbad00** [comment]
I clarified this in the readme.  The NSA, DISA, and Apple all recommend for maximum security to disable IPv6.  Apple states this on page 85 of https://www.apple.com/support/security/guides/docs/SnowLeopard_Security_Config_v10.6.pdf via the statement "If your organization’s network cannot use or does not require IPv6, turn it off."  The NSA and DISA state it in the respective links from the readme.

Why do they recommend this? This is likely simply a reduction of attack surface via the thinking that if you don't need it, get rid of it.  I don't have a specific reason to remove it beyond that.  The NSA and Apple released their guidance for 10.6 though (2009), and have not updated them so perhaps their views were also tinted by the fear that the functionality was too new and untested at the time.

That said, osxlockdown is not a one size fits all solution.  Although I am trying to think of ways to ensure someone can save a configuration to disable rules, upgrade to a newer version of osxlockdown, and still maintain their configuration.  Mostly, I wanted to record all the scripting needed to test and set the things I wanted.
