### ISSUE TITLE
Disable iCloud Drive

### ISSUE THREAD

**Issue by n10v** [SummitRoute/osxlockdown#5]
iCloud Drive is disabled on my Mac, but your program says what it's enabled
![2016-01-01 20 31 56](https://cloud.githubusercontent.com/assets/13235519/12071307/ceb4da52-b0c6-11e5-8c84-9a0e8276414a.png)
Or how I should disable it?

**Comment by astrostl** [comment]
You can see the commands used to both check and remediate at https://github.com/SummitRoute/osxlockdown/blob/master/commands.json

In this case, remediation is done by executing

`defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false`

You can find details about this setting at http://mjtsai.com/blog/2014/10/26/yosemite-uploads-unsaved-documents-and-recent-addresses-to-icloud/

**Comment by 0xdabbad00** [comment]
I need to do more testing to confirm how this rule really affects Cloud Drive.

**Comment by n10v** [comment]
Remediation command fix it
