### ISSUE TITLE
"Complex password required" check command doesn't work correctly

### ISSUE THREAD

**Issue by n10v** [SummitRoute/osxlockdown#6]
"Complex password required" check command is `pwpolicy -getglobalpolicy | tr \" \" \"\\n\" | grep requiresSymbol` but `tr` says:
![2016-01-01 20 41 47](https://cloud.githubusercontent.com/assets/13235519/12071330/1b3fc480-b0c8-11e5-9bcc-c8cbdd3f2c2b.png)

**Comment by astrostl** [comment]
Running from the CLI, I'm not sure that the `tr` is even necessary. Maybe just from the app?

```
osxlockdown astrostl$ sudo pwpolicy -setglobalpolicy "minChars=15 requiresNumeric=0"
osxlockdown astrostl$ sudo pwpolicy -getglobalpolicy|grep minChars=15
minChars=15 requiresNumeric=0
```

**Comment by 0xdabbad00** [comment]
You are correct, it's not required, I had copied/pasted that check from somewhere.  I've decided to just delete this check entirely, as noted in #11
