### ISSUE TITLE
Adapted it for Sierra, willing to contribute

### ISSUE THREAD

**Issue by roenass** [SummitRoute/osxlockdown#63]
Note, the build instructions also missed a "go get" for the yaml2 stuff.

diff --git a/commands.yaml b/commands.yaml
index a67c434..1e08b57 100644
--- a/commands.yaml
+++ b/commands.yaml
@@ -19,7 +19,7 @@
     defaults read /Library/Preferences/com.apple.Bluetooth ControllerPowerState | grep 0
   fix_command: |
     sudo defaults write /Library/Preferences/com.apple.Bluetooth ControllerPowerState -int 0; sudo killall -HUP blued
-  enabled: true
-  enabled: false
  - title: "Disable infrared receiver"
    @@ -35,14 +35,14 @@
    sudo defaults read com.apple.NetworkBrowser DisableAirDrop | grep 1
    fix_command: |
    defaults write com.apple.NetworkBrowser DisableAirDrop -bool YES
-  enabled: true
-  enabled: false

-- title: "Disable automatic setting of time and date"
+- title: "Set time and date automatically"
   check_command: |
-    sudo systemsetup getusingnetworktime | grep 'Network Time: Off'
-    sudo systemsetup getusingnetworktime | grep 'Network Time: On'
  fix_command: |
-    sudo systemsetup setusingnetworktime off
-    sudo systemsetup setusingnetworktime on
  enabled: true

@@ -150,13 +150,13 @@
   comment: "TODO: FileVault can be enabled with `fdesetup enable`, but you need to enter user creds and write down the recovery key. How to do this programmatically, or at least tell the user the steps?  See https://derflounder.wordpress.com/2013/10/22/managing-mavericks-filevault-2-with-fdesetup/"
   enabled: true
## 

+# If you set this in conjunction with hibernation, your Mac will not wake from sleep
- title: "Destroy File Vault Key when going to standby"
  check_command: |
   pmset -g | grep DestroyFVKeyOnStandby | grep 1
  fix_command: |
   sudo pmset -a destroyfvkeyonstandby 1
  -  enabled: true
  -  enabled: false
- title: "Enable hibernation mode (no memory power on sleep)"
  @@ -221,7 +221,7 @@
   networksetup -listallnetworkservices | while read i; do SUPPORT=$(networksetup -getinfo "$i" | grep "IPv6: Automatic") && if [ -n "$SUPPORT" ]; then exit 1; fi; done; exit 0
  fix_command: |
   networksetup -listallnetworkservices | while read i; do SUPPORT=$(networksetup -getinfo "$i" | grep "IPv6: Automatic") && if [ -n "$SUPPORT" ]; then networksetup -setv6off "$i"; fi; done;
  -  enabled: true
  -  enabled: false
- title: "Disable Previews"
  @@ -273,4 +273,11 @@
  check_command: |
   for i in /Applications/*/Contents/Info.plist; do URL=$(defaults read "$i" SUFeedURL 2>/dev/null | grep "http://"); if [ -n "$URL" ]; then exit 1; fi; done; exit 0
  comment: "For more details see https://vulnsec.com/2016/osx-apps-vulnerabilities/"
  -  enabled: false
    +
    +- title: "Disable PowerNap"
  -  check_command: |
  -    pmset -g | grep powernap | grep 0
  -  fix_command: |
  -      sudo pmset -a powernap 0
    enabled: true
    diff --git a/osxlockdown.go b/osxlockdown.go
    index 68373f8..1050013 100644
    --- a/osxlockdown.go
    +++ b/osxlockdown.go
    @@ -13,7 +13,7 @@ import (
    )
  
  // Version of osxlockdown
  -var Version = "0.9"
  +var Version = "0.9.1"
  
  // ReadFile takes a relative path and returns the bytes in that file
  func ReadFile(filename string) (data []byte, err error) {
  @@ -128,8 +128,8 @@ func main() {
  
  // Check OS version to make sure we will work
  osVersion := GetCommandOutput("system_profiler SPSoftwareDataType | grep \"System Version\" | cut -d: -f2")
  -   if !strings.Contains(osVersion, "OS X 10.11") {
  -       fmt.Println("ERROR: Unsupported OS. This tool was meant to be used only on OSX 10.11 (El Capitan)")
  -   if !strings.Contains(osVersion, "macOS 10.12")  {
  -       fmt.Println("ERROR: Unsupported OS. This tool was meant to be used only on macOS 10.12 (Sierra)")
    return
    }

**Comment by t56k** [comment]
Can you clarify this please?

> If you set this in conjunction with hibernation, your Mac will not wake from sleep

Does that mean if I'm about to install the beta I should change those settings back to their defaults?

**Comment by roenass** [comment]
Quoth cd-rum (19 Jul 2016, 8:57):

> Can you clarify this please?
> 
> > If you set this in conjunction with hibernation, your Mac will not wake from sleep
> 
> Does that mean if I'm about to install the beta I should change those settings back to their defaults?

I had this issue on El Capitan, and my final diagnose of the interplay between hibernation and destroying the FileVault key was:
- Mac goes to sleep
- FileVault key is destroyed
- Mac hibernates after a little while
- Mac is awoken
- But cannot read hibernation file (no access to storage, no FV key; I get _no_ FV auth screen, Mac shuts down
- First I suspected PowerNap had tried to wake the system intermediately, but even without PowerNap this still happens
- Mac must be rebooted

I've had this reproducably so on my MacBook; I modified the commands to reflect this.  Not using Filevault is not an option, so I've opted for hibernation without key amnesia rather than for key amnesia without hibernation.

So, you're fine if you hibernate without FileVault.  You're fine if you hibernate, use FileVault, and don't destroy the FileVault key upon sleep.  You're fine if you don't hibernate, use FileVault and destroy the FileVault key.

Not a beta issue.  And if others have had success in combining FV, FV key amnesia, and hibernation I'd be stymified.

**Comment by boetter** [comment]
What is the current Sierra version status?

**Comment by roenass** [comment]
Quoth Jacob Bøtter (24 Nov 2016, 10:24):

> What is the current Sierra version status?

I've changed a few of the checks, modified some of the code.

In particular, when enabling full hybernation *and* destroying the FileVault key in standby mode produces an unpleasant system state.

$ uname -a; ./osxlockdown
Darwin The-Book-of-Bokonon.local 16.3.0 Darwin Kernel Version 16.3.0: Wed Nov  9 19:52:37 PST 2016; root:xnu-3789.31.1~4/RELEASE_X86_64 x86_64
[PASSED] Verify all application software is current
[PASSED] Enable Auto Update
[PASSED] Disable infrared receiver
[PASSED] Set time and date automatically
[PASSED] Set an inactivity interval of 10 minutes or less for the screen saver
[PASSED] Enable secure screen saver corners
[PASSED] Require a password to wake the computer from sleep or screen saver
[PASSED] Ensure screen locks immediately when requested
[PASSED] Disable Remote Apple Events
[PASSED] Disable Remote Login
[PASSED] Disable Internet Sharing
[PASSED] Disable Screen Sharing
[PASSED] Disable Printer Sharing
[PASSED] Disable Wake on Network Access
[PASSED] Disable File Sharing
[PASSED] Disable Remote Management
[PASSED] Enable FileVault
[PASSED] Enable hibernation mode (no memory power on sleep)
[PASSED] Enable Gatekeeper
[PASSED] Enable Firewall
[PASSED] Enable Firewall Stealth Mode
[PASSED] Disable signed apps from being auto-permitted to listen through firewall
[PASSED] Disable iCloud drive
[PASSED] Require an administrator password to access system-wide preferences
[PASSED] Disable Previews
[PASSED] Secure Safari by crippling it
[PASSED] Disable automatic loading of remote content by Mail.app
[PASSED] Disable Captive Portal
[PASSED] Enable logging
[PASSED] Disable PowerNap
-------------------------------------------------------------------------------
osxlockdown 0.9.1
Date: 2016-11-24T10:54:51+01:00
SerialNumber: C02PG0H5FVH8
HardwareUUID: DD137A8E-7787-5EEA-B7CF-DD495CDA51EE
Final Score 100%; Pass rate: 30/30

**Comment by 0xdabbad00** [comment]
Please provide your changes to https://github.com/kristovatlas/osx-config-check or fork this project if you like.  I am no longer maintaining it.
