### ISSUE TITLE
"Require a password to wake the computer from sleep or screen saver"

### ISSUE THREAD

**Issue by virgilgh** [SummitRoute/osxlockdown#7]
not working on mine OSX, replace in commands.json line
"check_command": "defaults read com.apple.screensaver askForPassword | grep \"1\",
by
"check_command": "defaults read com.apple.screensaver askForPassword | grep 1",

in all cases, Thanks for this script.
Rgds

**Comment by astrostl** [comment]
Added to https://github.com/SummitRoute/osxlockdown/pull/10

I'd note, the check seems to work fine when run via `osxlockdown` - it doesn't when you paste the command literal from `commands.json` into a shell prompt. But since both work without quoting, this seems fine.

**Comment by 0xdabbad00** [comment]
Closing as related to #12 and this issue specifically is fixed via https://github.com/SummitRoute/osxlockdown/commit/5de80e2e8048ca69d160fbbafafa9b67480d3288
