### ISSUE TITLE
Tag the release with a version

### ISSUE THREAD

**Issue by streeter** [SummitRoute/osxlockdown#8]
Can you tag a release with a version? Something like '0.1' or whatever version scheme you want to start with.

**Comment by sroberts** [comment]
Yeah, this is also the proper way to distribute binaries rather than putting it in the repo itself. Git really doesn't like big binary files like that.

**Comment by astrostl** [comment]
+1 for not checking the binary into the repo

**Comment by 0xdabbad00** [comment]
Done.

**Comment by sroberts** [comment]
@0xdabbad00 Awesome to see, thanks for moving this so quickly, great project!
