### ISSUE TITLE
[FAILED] Require an administrator password to access system-wide preferences

### ISSUE THREAD

**Issue by astrostl** [SummitRoute/osxlockdown#9]
As per the latest JSON, remediation is done via

`"fix_command": "security authorizationdb read system.preferences > /tmp/system.preferences.plist &&/usr/libexec/PlistBuddy -c \"Set :shared false\" /tmp/system.preferences.plist && security authorizationdb write system.preferences < /tmp/system.preferences.plist",`

this command appears to be bogus with a standard user or sudo, yielding

```
YES (0)
Unrecognized Command
```

and failing subsequent checks.

**Comment by astrostl** [comment]
Quotes strike again: `/usr/libexec/PlistBuddy -c "Set :shared false" /tmp/system.preferences.plist` works from the CLI, the difference being that the JSON command escapes the quotation marks.

I run the checks and remediations manually, I think a lot of others do as well. Can anything be done to get commands which are all terminal-pastable?

**Comment by 0xdabbad00** [comment]
Looks like the best way to do this will be to change to using TOML instead of JSON for the file format.  Recorded as a new feature to work on in #12 Closing this issue as it's not specifically a bug.
